version: "2"

services:
  logic-stack-client:
    build: ./client
    image: "mhedev/logic-stack-client:0.0.1"
    container_name: "logic-stack-client"
    hostname: "logic-stack-client"
    environment:
      SERVICE_NAME: "logic-stack-client"
      HOST: 0.0.0.0
      PORT: 8080
    volumes:
      - ./client:/usr/src/app
    ports:
      - "8080:8080"
      
  logic-stack-server:
    build: ./server
    image: "mhedev/logic-stack-server:0.0.1"
    container_name: "logic-stack-server"
    hostname: "logic-stack-server"
    environment:
      SERVICE_NAME: "logic-stack-server"
      HOST: 0.0.0.0
      PORT: 8081
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8081:8081"
