server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /**

jwt:
  headerAuthorizationKey: Authorization
  tokenBearerPrefix: "Bearer "
  roleName: role
  defaultRoleValue: WHITELIST_MANAGER
  clientSecret: "{ABCInetum_123456789_!@#$%&/()$=-acbdefghijklmnñopqrstuvwxyz-clientSecretKey}"
  issuerInfo: "https://www.inetum.com/"
  tokenExpirationMinutes: 60
