export const SHOW_LOADING = 'LOADING-SERVICE/SHOW-LOADING';
export const SHOW_LOADING_OK = 'LOADING-SERVICE/SHOW-LOADING-OK';
export const SHOW_LOADING_KO = 'LOADING-SERVICE/SHOW-LOADING-KO';
export const HIDE_LOADING = 'LOADING-SERVICE/HIDE-LOADING';